I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 252, in script
    elsa "Госпожа Торелин, герцог ждёт вас внизу."
Exception: Sayer 'elsa' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 252, in script
    elsa "Госпожа Торелин, герцог ждёт вас внизу."
  File "C:\Users\Sofia\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\Sofia\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Sofia\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'elsa' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
visual_novel_ck 1.0
Tue Feb 25 20:54:14 2025
